name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  basic:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Lint
        run: npm run lint